CREATE TABLE product (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL UNIQUE,
    product_category_id INTEGER,
    description TEXT,
    mrp NUMERIC(10, 2) NOT NULL,
    sales_price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    landing_price NUMERIC(18, 2) NOT NULL DEFAULT 18.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER NOT NULL,
    modified_at TIMESTAMP,
    modified_by INTEGER,

    CONSTRAINT fk_product_category FOREIGN KEY (product_category_id)
        REFERENCES product_category(product_category_id),

    CONSTRAINT fk_created_by FOREIGN KEY (created_by)
        REFERENCES users(user_id),

    CONSTRAINT fk_modified_by FOREIGN KEY (modified_by)
        REFERENCES users(user_id)
);
